#ifndef __ARCH_SH_CPU_UBC_H__
#define __ARCH_SH_CPU_UBC_H__

enum {
	SH_BREAKPOINT_READ	= (1 << 2),
	SH_BREAKPOINT_WRITE	= (1 << 3),
	SH_BREAKPOINT_RW	= SH_BREAKPOINT_READ | SH_BREAKPOINT_WRITE,

	SH_BREAKPOINT_LEN_1	= (1 << 0),
	SH_BREAKPOINT_LEN_2	= (1 << 1),
	SH_BREAKPOINT_LEN_4	= SH_BREAKPOINT_LEN_1 | SH_BREAKPOINT_LEN_2,
};

#endif /* __ARCH_SH_CPU_UBC_H__ */
