obj-$(CONFIG_PL320_MBOX)	+= pl320-ipc.o

obj-$(CONFIG_MAILBOX)		+= mailbox.o
obj-$(CONFIG_OMAP1_MBOX)	+= mailbox-omap1.o
obj-$(CONFIG_OMAP2PLUS_MBOX)	+= mailbox-omap2.o
obj-$(CONFIG_DBX500_MBOX)	+= mailbox-dbx500.o
